### ISSUE TITLE
Docker: Unable to find image

### ISSUE THREAD

**Issue by doroved** [m1guelpf/tinyvector-rs#2]
<img width="712" alt="image" src="https://github.com/m1guelpf/tinyvector/assets/30116541/30fd49cf-7f51-4c9b-a77c-a068140ddc9a">

**Comment by m1guelpf** [comment]
hmmm, guessing this is because the image is only available for amd64, could you see if `--platform linux/amd64` fixes it?

**Comment by doroved** [comment]
> --platform linux/amd64

Yes, everything is ok now
